---

- hosts: masters,workers
  tasks:    

    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: create containerd config file
      file:
        path: /etc/modules-load.d/containerd.conf
        state: touch

    - name: add conf for containerd
      blockinfile:
        path: /etc/modules-load.d/containerd.conf
        block: |
              overlay
              br_netfilter

    - name: run modprobe
      shell: |
              modprobe overlay
              modprobe br_netfilter

    - name: config file for k8s networking
      file:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        state: touch

    - name: add conf for containerd
      blockinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        block: |
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1
                net.bridge.bridge-nf-call-ip6tables = 1

    - name: apply new settings...
      command: sudo sysctl --system

    - name: Update the packages cache
      apt: 
        update_cache: yes

    - name: Install containerd
      apt: 
        name:
          - containerd
        state: present

    - name: create directory
      file:
        path: /etc/containerd
        state: directory

    - name: create containerd default config
      shell: |
               sudo containerd config default | sudo tee /etc/containerd/config.toml

    - name: 
      service:
        name: containerd
        state: restarted

    - name: disable swap
      shell: |
              sudo swapoff -a
              sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Update the packages cache
      apt: 
        update_cache: yes

    - name: install utilities
      apt: 
        name:
          - apt-transport-https
          - curl
        state: present

    - name: Get docker GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    
    - name: add kubeadm repo
      apt_repository:
        repo: deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
        mode: 0600
    
    - name: Update the packages cache
      apt: 
        update_cache: yes

    - name: Install kubeadm and kubelet
      apt: 
        name:
          - kubeadm
          - kubelet
        state: present

    - name: Install kubectl only on master
      apt: 
        name:
          - kubectl
        state: present
      when: noderole == "master"

    - name: hold kubeadm
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: hold kubeadm
      dpkg_selections:
        name: kubelet
        selection: hold

    - name: hold kubeadm
      dpkg_selections:
        name: kubectl
        selection: hold
      when: noderole == "master"

- hosts: master
  tasks:
    - name: run kubeadm init to setup master
      shell: kubeadm init
      ignore_errors: yes
      
    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory

    - name: copy kubeconfig find to .kube dir
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes

    - name: install calico plugin
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: get the token for joining the worker node
      shell: kubeadm token create  --print-join-command
      register: k8s_join_command

    - name: copy k8s join token to tmp file locally
      local_action: copy content="{{ k8s_join_command.stdout_lines[0] }}" dest="/tmp/k8s_join_command"


- hosts: workers
  tasks:
    - name: copy join command to worker node
      copy:
        src: /tmp/k8s_join_command
        dest: /tmp/k8s_join_command
        mode: 0777

    - name: join worker node to th cluster 
      command: sh /tmp/k8s_join_command
      register: join_output

    - debug:
        var: "{{ join_output }}"
